export const LUNCH_LOADING = "LUNCH_LOADING";
export const GET_LUNCH = "GET_LUNCH";
export const LUCNH_FAILED = "LUNCH_FAILED";

export const DINNER_LOADING = "DINNER_LOADING";
export const GET_DINNER = "GET_DINNER";
export const DINNER_FAILED = "DINNER_FAILED";

export const GET_IMAGES = "GET_IMAGES";
export const IMAGES_REFRESHING = "IMAGES_REFRESHING";
export const IMAGES_LOADING = "IMAGES_LOADING";
export const IMAGES_FAILED = "IMAGES_FAILED";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const POST_BOOKING_LOADING = "POST_BOOKING_LOADING";
export const GET_POST_RESPONSE = "GET_POST_RESPONSE";
export const POST_FAILED = "POST_FAILED";

export const SUBSCRIBE_LOADING = "SUBSCRIBE_LOADING";
export const GET_SUBSCRIBE_RESONSE= "GET_SUBSCRIBE_RESPONSE";
export const SUBSCRIBE_FAILED= "SUBSCRIBE_FAILED";

export const ENQUIRY_LOADING = "ENQUIRY_LOADING";
export const GET_ENQUIRY_RESPONSE = "GET_ENQUIRY_RESPONSE";
export const ENQUIRY_FAILED = "ENQUIRY_FAILED";





